services:
  # MCP Server - Main application
  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "8080:8080"
    environment:
      - TRANSPORT_TYPE=http
      - HTTP_PORT=8080
      - HTTP_HOST=0.0.0.0
      - LOG_LEVEL=info
      - PROTOCOL_VERSION=2025-06-18
      - SERVER_NAME=basic-mcp-server
      - SERVER_VERSION=1.0.0
      - ENABLE_CORS=true
      - AUTH_ENABLED=false
      - RATE_LIMIT_ENABLED=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

  # MCP Inspector for debugging MCP servers
  # Note: The official image binds to localhost only, so we use network_mode: host
  # to make it accessible from the host machine
  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    container_name: agentflare-mcp-inspector
    restart: unless-stopped
    network_mode: host
    environment:
      DANGEROUSLY_OMIT_AUTH: "true"

networks:
  mcp-network:
    driver: bridge